# Header

menu:
  主页: /
  another world: /geek

# SubNav
subnav:
  github: "https://github.com/Michael1015198808"
  weibo: "https://weibo.com/p/1005053911976060"
  rss: /atom.xml
  #psn: "#"
  zhihu: "https://www.zhihu.com/people/yan-zhen-yu-89-16"
  douban: "https://www.douban.com/people/153751793"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/169316082"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  facebook: "https://www.facebook.com/profile.php?id=100009286741709"
  #instagram: "https://www.instagram.com/michael1015198808/"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
reward_wording: '谢谢你请我吃糖果'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '不存在的目录'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /images/portrait.jpeg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
#changyan_appid: 'cysX3aGWt'
#changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
#disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '最近在做'
  proverb: '箴言'

friends:
    #黄秉焜: https://congee524.github.io/
  张天昀: https://doowzs.com/
  匡舒磊: https://shelah-kuang.github.io/
  Maxwell Lyu: https://maxwell-lyu.github.io/
  萌捷列夫: https://mengzelev.github.io/
  Jude: https://judie1999.github.io/
  lynx: https://niabie.github.io/
  Jarvis Zhang: https://jarviszl.github.io/
  Marukohe He: https://marukohe.github.io/
  Larry Yin: https://larryytr.github.io/
  梁宇方: https://lanceloia.github.io/
  xy: https://nju-xy.github.io/
  forewing : https://jbesu.com/
  友情链接互挂帮助: /files/friend-link.html

intro:
  张天昀: 19岁，是学生。
  萌捷列夫: 好时代，来临吧！
  匡舒磊: 落败孤岛孤落败
  forewing: 爱慕拆妮子

aboutme: "
<ul>
<br><br>
    <li> <h1>学：</h1>
        日语
            <h5>词汇量大概50-70吧(笑)</h5>
            <h6>(这两个数字是在缓慢地动态变化的)</h6>
        英语
            <h5>听力和阅读为主</h5>
        vi&vim
            <h5>想配出最酷（sao）的vim！</h5>
<br><br>
    <li> <h1>做：</h1>
        背单词小工具<a href=\"/2019/04/21/zsh-vocab开发心路历程/\">zsh-vocab</a>
<br><br><br>
    <li><a href=\"/files/intro.html\"> More info </a>
</ul>
"

proverb: '
""我们必须知道，我们终将知道"<br>
——大卫·希尔伯特<br><br>
"我们生活在阴沟里，依然能够仰望天空"<br>
——奥斯卡·王尔德
'

valine:
    appid: uLiRl9PVCoTJtRGlF7vcpqWk-gzGzoHsz
    appkey: jiNB6sTJ99mzmXbTER3fYyF2
    verify: false
    notify: true
    avatar: mm
    placeholder: Say something?
