# Header

menu:
  主页: /
  another world: /geek

# SubNav
subnav:
  github: "https://github.com/Michael1015198808"
  weibo: "https://weibo.com/p/1005053911976060"
  #rss: /atom.xml
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
reward_wording: '谢谢你请我吃糖果'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '不存在的目录'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /images/portrait.jpeg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
#changyan_appid: 'cysX3aGWt'
#changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
#disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'
  proverb: '箴言'

friends:
  黄秉焜: https://congee524.github.io/
  张天昀: https://doowzs.com/
  萌捷列夫: https://mengzelev.github.io
  Maxwell Lyu: https://maxwell-lyu.github.io/

intro:
  张天昀: 19岁，是学生。
  萌捷列夫: 好时代，来临吧！

aboutme: "
<ul>
    <li> <h1>最近在做：</h1>
        之前欠下的PA作业<br>
        <a href=\"/2019/01/14/2019寒假计划/\">寒假规划</a>
<br>
    <br><li> <h1>最近在学：</h1>
        法语
            <h5>词汇量大概30-40吧(笑)</h5>
            <h6>(这两个数字是在缓慢地动态变化的)</h6>
        <br>英语
            <h5>感觉听力和阅读应该挺稳的</h5>
    <br><li> <h1>最近在玩：</h1>
        PVZ2(国际版)
            <h5>只玩battlez和每日三刷碎片两次</h5>
            <h5>氪了一只冰龙草$4.99</h5>
    <li><a href=\"/1999/03/26/我\"> More info </a>
</ul>
"

proverb: 产生了某些bug，等待修复(预计要两周)<br>
